# Generated by Django 5.0.7 on 2024-08-20 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('polls', '0007_question_available_agentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentclient',
            name='agent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentclient',
            name='api_key',
            field=models.CharField(default='akka', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentclient',
            name='base_url',
            field=models.URLField(default='foo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentclient',
            name='label',
            field=models.TextField(default="a"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='client',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='agents.agentclient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='model',
            field=models.TextField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
