# Generated by Django 5.0.7 on 2024-08-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentclient_agent_agentclient_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentclient',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='agentclient',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
