# Generated by Django 5.0.7 on 2024-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentclient_slug_alter_agentclient_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsettings',
            name='temperature',
            field=models.FloatField(default=1.0),
        ),
    ]
