# Generated by Django 5.0.7 on 2024-11-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_clientsettings_temperature'),
        ('polls', '0022_alter_crowd_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentclient',
            name='agent',
        ),
        migrations.CreateModel(
            name='AutoAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('ClientSettings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.clientsettings')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.agent')),
            ],
        ),
    ]
