# Generated by Django 5.0.7 on 2024-11-25 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentclient_owner'),
        ('polls', '0022_alter_crowd_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoagent',
            name='ClientSettings',
        ),
        migrations.CreateModel(
            name='AutoVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_votes', models.IntegerField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('client_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.clientsettings')),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questiongroup')),
            ],
        ),
        migrations.AddField(
            model_name='autoagent',
            name='autovote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agents.autovote'),
            preserve_default=False,
        ),
    ]
