# Generated by Django 5.0.7 on 2024-11-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_remove_autoagent_clientsettings_autovote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentclient',
            name='default_prompt',
            field=models.TextField(default='', max_length=100),
        ),
    ]
