# Generated by Django 5.0.7 on 2024-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentclient_default_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentclient',
            name='label',
            field=models.CharField(max_length=500),
        ),
    ]
