# Generated by Django 5.0.7 on 2024-11-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_agentclient_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentclient',
            name='default_prompt',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentclient',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
