# Generated by Django 5.0.7 on 2024-11-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agentclient_default_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentclient',
            name='api_key',
            field=models.CharField(max_length=1000),
        ),
    ]
