# Generated by Django 5.0.7 on 2024-11-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_agentclient_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='autovote',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
