# Generated by Django 5.0.7 on 2024-11-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_autovote_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autovote',
            name='duration',
        ),
        migrations.AddField(
            model_name='autoagent',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
