# Generated by Django 5.0.7 on 2024-07-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
