# Generated by Django 5.0.7 on 2024-08-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_image',
        ),
        migrations.AddField(
            model_name='question',
            name='question_image_path',
            field=models.FilePathField(null=True),
        ),
    ]
