# Generated by Django 5.0.7 on 2024-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_question_image_path_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='score',
            field=models.BigIntegerField(default=1),
        ),
    ]
