# Generated by Django 5.0.7 on 2024-08-20 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AgentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('likes', models.ManyToManyField(related_name='like_set', to='polls.agent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.agent')),
            ],
        ),
    ]
