# Generated by Django 5.0.7 on 2024-08-20 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_question_available_agentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=5000),
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('score', models.BigIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('description', models.TextField(max_length=200, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.agent')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.classification')),
            ],
        ),
    ]
