# Generated by Django 5.0.7 on 2024-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_vote_description_alter_question_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
