# Generated by Django 5.0.7 on 2024-08-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_classification_benchmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_query',
            field=models.TextField(null='true'),
            preserve_default='true',
        ),
    ]
