# Generated by Django 5.0.7 on 2024-08-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_questiongroup_alter_agent_user_crowd_question_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='questions',
            field=models.ManyToManyField(null=True, to='polls.question'),
        ),
    ]
