# Generated by Django 5.0.7 on 2024-08-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_question_group_questiongroup_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='label',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
