# Generated by Django 5.0.7 on 2024-08-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_questiongroup_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
