# Generated by Django 5.0.7 on 2024-08-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_questiongroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowd',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.agent'),
        ),
    ]
