# Generated by Django 5.0.7 on 2024-08-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_crowd_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowd',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='questions',
            field=models.ManyToManyField(to='polls.question'),
        ),
    ]
