# Generated by Django 5.0.7 on 2024-08-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_crowd_session_alter_questiongroup_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowd',
            name='session',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='crowd',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='crowd',
            name='sex',
            field=models.CharField(null=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='classification',
            name='score',
            field=models.BigIntegerField(default=100),
        ),
    ]
