# Generated by Django 5.0.7 on 2024-09-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_remove_crowd_session_remove_question_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowd',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
