# Generated by Django 5.0.7 on 2024-09-15 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_crowd_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowd',
            name='duration',
        ),
    ]
