# Generated by Django 5.0.7 on 2024-09-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_remove_crowd_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowd',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
