# Generated by Django 5.0.7 on 2024-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_crowd_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowd',
            name='sex',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
