# Generated by Django 5.0.7 on 2024-11-28 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_crowd_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precision', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('recall', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('p_certainty', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('n_certainty', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('main_personality', models.CharField(max_length=10)),
                ('secondary_personality', models.CharField(max_length=10)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.agent')),
            ],
        ),
    ]
