# Generated by Django 5.0.7 on 2024-11-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_agentmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmetrics',
            name='main_personality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agentmetrics',
            name='secondary_personality',
            field=models.CharField(max_length=100),
        ),
    ]
